(() => {
 const words={
 fr:{language:'Langue',title:'Un peu plus de caractère.',intro:'Les mêmes personnages. Des réactions courtes, à tester avant intégration.',reduced:'Mouvements réduits',system:'Préférence système active',replay:'Revoir',scope:'Aperçu visuel seulement. Aucun changement de paddle, collision, mouvement de combat, score ou sauvegarde. Les battements d’ailes existants restent la référence.',previous:'Revoir A03 / A04 →',idle:'Prêts à jouer',prompt:'Choisis une réaction. Aucun mouvement ne démarre automatiquement.',still:'Version sobre · sans déplacement',duration:'Durée',group:'Réactions',events:{flight:['Vol','Une légère inclinaison accompagne le vol. Tarantula suit Aracne du regard.'],effort:['Effort','Aracne se penche brièvement. Tarantula l’encourage.'],impact:['Impact','Un court recul local. Tarantula réagit : attention ! Aucun flash d’écran.'],discovery:['Découverte','Aracne se redresse. Tarantula acquiesce : bonne réponse.'],victory:['Victoire','Une courte montée, puis retour au repos. Tarantula salue la réussite.']}},
 it:{language:'Lingua',title:'Un po’ più di carattere.',intro:'Gli stessi personaggi. Reazioni brevi, da provare prima dell’integrazione.',reduced:'Movimento ridotto',system:'Preferenza di sistema attiva',replay:'Rivedi',scope:'Solo anteprima visiva. Nessuna modifica a piattaforma, collisioni, movimenti di battaglia, punteggio o salvataggi. Il battito d’ali esistente resta il riferimento.',previous:'Rivedi A03 / A04 →',idle:'Pronti a giocare',prompt:'Scegli una reazione. Nessun movimento parte automaticamente.',still:'Versione sobria · senza spostamenti',duration:'Durata',group:'Reazioni',events:{flight:['Volo','Una leggera inclinazione accompagna il volo. Tarantula segue Aracne.'],effort:['Sforzo','Aracne si inclina per un istante. Tarantula la incoraggia.'],impact:['Impatto','Un breve arretramento locale. Tarantula avverte: attenzione! Nessun flash sullo schermo.'],discovery:['Scoperta','Aracne si rialza. Tarantula annuisce: risposta corretta.'],victory:['Vittoria','Una breve salita, poi ritorno a riposo. Tarantula celebra il successo.']}},
 en:{language:'Language',title:'A little more character.',intro:'The same characters. Short reactions to try before integration.',reduced:'Reduced motion',system:'System preference active',replay:'Replay',scope:'Visual preview only. No changes to paddle, collisions, battle movement, scores or saves. Existing wingbeats remain the reference.',previous:'Review A03 / A04 →',idle:'Ready to play',prompt:'Choose a reaction. Nothing animates automatically.',still:'Quiet version · no movement',duration:'Duration',group:'Reactions',events:{flight:['Flight','A gentle tilt accompanies flight. Tarantula follows Aracne.'],effort:['Effort','Aracne leans briefly. Tarantula encourages her.'],impact:['Impact','A short local recoil. Tarantula reacts: watch out! No screen flash.'],discovery:['Discovery','Aracne lifts up. Tarantula nods: correct answer.'],victory:['Victory','A short rise, then back to rest. Tarantula celebrates the win.']}},
 es:{language:'Idioma',title:'Un poco más de carácter.',intro:'Los mismos personajes. Reacciones breves para probar antes de integrar.',reduced:'Movimiento reducido',system:'Preferencia del sistema activa',replay:'Repetir',scope:'Solo vista previa. Sin cambios en barra, colisiones, movimientos de batalla, puntuación o partidas guardadas. El aleteo existente sigue siendo la referencia.',previous:'Revisar A03 / A04 →',idle:'Listos para jugar',prompt:'Elige una reacción. Ningún movimiento empieza automáticamente.',still:'Versión suave · sin movimiento',duration:'Duración',group:'Reacciones',events:{flight:['Vuelo','Una inclinación suave acompaña el vuelo. Tarantula sigue a Aracne.'],effort:['Esfuerzo','Aracne se inclina brevemente. Tarantula la anima.'],impact:['Impacto','Un retroceso breve y local. Tarantula avisa: ¡cuidado! Sin destellos en pantalla.'],discovery:['Descubrimiento','Aracne se eleva. Tarantula asiente: respuesta correcta.'],victory:['Victoria','Una subida breve y regreso al reposo. Tarantula celebra el éxito.']}}
 };
 const motions={flight:{duration:480,bird:['rotate(0deg)','rotate(-6deg)','rotate(0deg)'],spider:['rotate(0deg)','rotate(3deg)','rotate(0deg)'],marks:['↗','…']},effort:{duration:240,bird:['rotate(0deg)','rotate(-10deg)','rotate(0deg)'],spider:['translateY(0)','translateY(-3px)','translateY(0)'],marks:['↗','!']},impact:{duration:180,bird:['translateX(0)','translateX(-5px)','translateX(0)'],spider:['rotate(0deg)','rotate(-5deg)','rotate(0deg)'],marks:['!','!']},discovery:{duration:420,bird:['translateY(0)','translateY(-6px)','translateY(0)'],spider:['translateY(0)','translateY(3px)','translateY(0)'],marks:['✓','✓']},victory:{duration:650,bird:['translateY(0) rotate(0deg)','translateY(-12px) rotate(-6deg)','translateY(0) rotate(0deg)'],spider:['rotate(0deg)','rotate(6deg)','rotate(-4deg)','rotate(0deg)'],marks:['★','✓']}};
 const $=s=>document.querySelector(s),media=window.matchMedia('(prefers-reduced-motion: reduce)');
 let language='fr',selected=null,animations=[];
 function stop(){animations.forEach(a=>a.cancel());animations=[];}
 const reduced=()=>media.matches||$('#reduced').checked;
 function render(){const w=words[language];document.documentElement.lang=language;document.querySelectorAll('[data-text]').forEach(el=>el.textContent=w[el.dataset.text]);$('.events').setAttribute('aria-label',w.group);$('#system-preference').textContent=media.matches?w.system:'';$('#reduced').disabled=media.matches;if(media.matches)$('#reduced').checked=true;document.querySelectorAll('[data-event]').forEach(b=>{b.textContent=w.events[b.dataset.event][0];b.setAttribute('aria-pressed',String(b.dataset.event===selected));});$('#event-label').textContent=selected?w.events[selected][0]:w.idle;$('#event-description').textContent=selected?w.events[selected][1]:w.prompt;$('#duration').textContent=reduced()?w.still:selected?`${w.duration} · ${motions[selected].duration} ms`:'';$('#replay').disabled=!selected;}
 function play(event){stop();selected=event;const motion=motions[event];$('#bird-reaction').textContent=motion.marks[0];$('#spider-reaction').textContent=motion.marks[1];render();if(reduced())return;for(const id of ['bird','spider']){const el=$('#'+id);if(el.animate)animations.push(el.animate(motion[id].map(transform=>({transform})),{duration:motion.duration,easing:'ease-out',iterations:1}));}}
 document.querySelectorAll('[data-event]').forEach(b=>b.addEventListener('click',()=>play(b.dataset.event)));
 $('#replay').addEventListener('click',()=>{if(selected)play(selected);});$('#language').addEventListener('change',e=>{stop();language=e.target.value;render();});$('#reduced').addEventListener('change',()=>{stop();render();});media.addEventListener('change',()=>{stop();render();});document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);render();
})();
