import { LANG } from '../i18n.js';
const messages = {
  fr: {
    battleOrientation: "Pour jouer confortablement, tourne ton téléphone en paysage.", battleStars: "Étoiles",
    huntOrientation: "Pour la chasse, garde ton téléphone en mode portrait.",
    rotatePortrait: "Tourne ton téléphone à la verticale pour continuer la chasse.",
    rotateLandscape: "Tourne ton téléphone en paysage pour commencer la bataille.",
    landscapeReady: "Parfait — orientation paysage détectée.",
    huntComplete: "Chasse terminée · 10/10",
    bossIncoming: "Le gardien du territoire apparaît…",
    pause: "Pause", resume: "Reprendre", restartLevel: "Recommencer le niveau", discoveries: "Mes découvertes",
    pauseHint: "Le jeu est en pause.", performance: "Performance", fps: "FPS", jank: "Saccades", worstFrame: "Pire frame",
    testTools: "Raccourcis de test",
    testWarning: "Outils temporaires. Simuler une victoire modifie la progression sur cet appareil.",
    testWin: "Simuler une victoire",

    musicStart: "Activer la musique",
    musicStop: "Couper la musique",
    installApp: "Installer l’app",

    hofLead: "Les meilleurs scores sont enregistrés sur cet appareil.",
    points: "Points cumulés",
    runs: "Parties enregistrées",
    players: "Joueurs uniques",
    emptyScores: "Aucun score enregistré. Termine une chasse pour ajouter ton score.",
    localScores: "Les scores sont conservés dans ce navigateur.",
    country: "Pays",
    progress: "Progression",
    hits: "Coups",
    time: "Temps",
    bonusDetail: "Détail bonus",

    defeat: 'Défaite…',
    language: 'Langue', ready: 'Prêt·e pour la chasse ?', lead: 'Explore le Salento, collecte les trésors et gagne les batailles pour débloquer les cartes.',
    start: 'Lancer la chasse', bonus: 'Mes découvertes', home: 'Accueil', loading: 'Chargement…', level: 'Niveau',
    continue: 'Continuer la chasse', replay: 'Rejouer', replayLevel: 'Rejouer un niveau', newGame: 'Nouvelle partie', chooseLevel: 'Choisir un niveau', confirmNewGame: 'Effacer la progression de cette partie et recommencer au niveau 1 ?', confirm: 'Oui, recommencer', cancel: 'Annuler', complete: 'Les neuf chasses sont terminées !',
    bonusLead: 'La chasse continue. Les visites et les QR sont facultatifs : explore-les à ton rythme.',
    maps: 'Explorer une carte', mapHint: 'Retrouve les lieux dans le Salento réel.', open: 'Explorer', locked: 'À débloquer',
    passport: 'Passeport et QR', passportHint: 'Retrouve tes visites et valide un QR code.', passportOpen: 'Ouvrir mon passeport',
    more: 'Classements', won: 'Bataille gagnée !', unlocked: 'Carte débloquée',
    name: 'Ton nom / pseudo ?', player: 'Joueur', editPlayer: 'Modifier', briefing: 'Ta mission', mission: 'Trouve les dix lieux indiqués, puis remporte la bataille.',
    reward: 'Gagne la bataille pour débloquer la carte réelle.', battle: 'Bataille', fight: 'Commencer la bataille',
    battleHint: 'En paysage : ← / → pour bouger, ↑ pour sauter, A pour attaquer, B pour le spécial.',
  },
  it: {
    battleOrientation: "Per giocare comodamente, ruota il telefono in orizzontale.", battleStars: "Stelle",
    huntOrientation: "Per la caccia, tieni il telefono in verticale.",
    rotatePortrait: "Ruota il telefono in verticale per continuare la caccia.",
    rotateLandscape: "Ruota il telefono in orizzontale per iniziare la battaglia.",
    landscapeReady: "Perfetto — orientamento orizzontale rilevato.",
    huntComplete: "Caccia completata · 10/10",
    bossIncoming: "Il guardiano del territorio appare…",
    pause: "Pausa", resume: "Riprendi", restartLevel: "Ricomincia il livello", discoveries: "Le mie scoperte",
    pauseHint: "Il gioco è in pausa.", performance: "Prestazioni", fps: "FPS", jank: "Scatti", worstFrame: "Frame peggiore",
    testTools: "Scorciatoie di test",
    testWarning: "Strumenti temporanei. Simulare una vittoria modifica i progressi su questo dispositivo.",
    testWin: "Simula una vittoria",

    musicStart: "Attiva la musica",
    musicStop: "Disattiva la musica",
    installApp: "Installa l’app",

    hofLead: "I migliori punteggi sono salvati su questo dispositivo.",
    points: "Punti totali",
    runs: "Partite salvate",
    players: "Giocatori",
    emptyScores: "Nessun punteggio salvato. Completa una caccia per aggiungerlo.",
    localScores: "I punteggi sono conservati in questo browser.",
    country: "Paese",
    progress: "Progressi",
    hits: "Colpi",
    time: "Tempo",
    bonusDetail: "Dettagli bonus",

    defeat: 'Sconfitta…',
    language: 'Lingua', ready: 'Pronti per la caccia?', lead: 'Esplora il Salento, raccogli i tesori e vinci le battaglie per sbloccare le mappe.',
    start: 'Inizia la caccia', bonus: 'Le mie scoperte', home: 'Inizio', loading: 'Caricamento…', level: 'Livello',
    continue: 'Continua la caccia', replay: 'Gioca di nuovo', replayLevel: 'Rigioca un livello', newGame: 'Nuova partita', chooseLevel: 'Scegli un livello', confirmNewGame: 'Cancellare i progressi di questa partita e ricominciare dal livello 1?', confirm: 'Sì, ricomincia', cancel: 'Annulla', complete: 'Hai completato tutte e nove le cacce!',
    bonusLead: 'La caccia continua. Visite e QR sono facoltativi: esplorali quando vuoi.',
    maps: 'Esplora una mappa', mapHint: 'Ritrova i luoghi nel Salento reale.', open: 'Esplora', locked: 'Da sbloccare',
    passport: 'Passaporto e QR', passportHint: 'Ritrova le tue visite e convalida un codice QR.', passportOpen: 'Apri il passaporto',
    more: 'Classifiche', won: 'Battaglia vinta!', unlocked: 'Mappa sbloccata',
    name: 'Il tuo nome / soprannome?', player: 'Giocatore', editPlayer: 'Modifica', briefing: 'La tua missione', mission: 'Trova i dieci luoghi indicati, poi vinci la battaglia.',
    reward: 'Vinci la battaglia per sbloccare la mappa reale.', battle: 'Battaglia', fight: 'Inizia la battaglia',
    battleHint: 'In orizzontale: ← / → per muoverti, ↑ per saltare, A per attaccare, B per lo speciale.',
  },
  en: {
    battleOrientation: "For comfortable play, turn your phone to landscape.", battleStars: "Stars",
    huntOrientation: "Keep your phone in portrait for the hunt.",
    rotatePortrait: "Turn your phone upright to continue the hunt.",
    rotateLandscape: "Turn your phone to landscape to start the battle.",
    landscapeReady: "Perfect — landscape orientation detected.",
    huntComplete: "Hunt complete · 10/10",
    bossIncoming: "The territory guardian appears…",
    pause: "Pause", resume: "Resume", restartLevel: "Restart level", discoveries: "My discoveries",
    pauseHint: "The game is paused.", performance: "Performance", fps: "FPS", jank: "Jank", worstFrame: "Worst frame",
    testTools: "Test shortcuts",
    testWarning: "Temporary tools. Simulating a win changes progress on this device.",
    testWin: "Simulate a win",

    musicStart: "Enable music",
    musicStop: "Mute music",
    installApp: "Install app",

    hofLead: "Best scores are saved on this device.",
    points: "Total points",
    runs: "Saved games",
    players: "Players",
    emptyScores: "No scores yet. Finish a hunt to add your score.",
    localScores: "Scores are stored in this browser.",
    country: "Country",
    progress: "Progress",
    hits: "Hits",
    time: "Time",
    bonusDetail: "Bonus details",

    defeat: 'Defeat…',
    language: 'Language', ready: 'Ready for the hunt?', lead: 'Explore Salento, collect treasures and win battles to unlock the maps.',
    start: 'Start the hunt', bonus: 'My discoveries', home: 'Home', loading: 'Loading…', level: 'Level',
    continue: 'Continue the hunt', replay: 'Play again', replayLevel: 'Replay a level', newGame: 'New game', chooseLevel: 'Choose a level', confirmNewGame: 'Erase this game progress and restart from level 1?', confirm: 'Yes, restart', cancel: 'Cancel', complete: 'All nine hunts completed!',
    bonusLead: 'The hunt continues. Visits and QR codes are optional: explore them at your own pace.',
    maps: 'Explore a map', mapHint: 'Find the places in real-world Salento.', open: 'Explore', locked: 'Locked',
    passport: 'Passport and QR', passportHint: 'View your visits and validate a QR code.', passportOpen: 'Open my passport',
    more: 'Rankings', won: 'Battle won!', unlocked: 'Map unlocked',
    name: 'Your name / nickname?', player: 'Player', editPlayer: 'Edit', briefing: 'Your mission', mission: 'Find the ten places indicated, then win the battle.',
    reward: 'Win the battle to unlock the real-world map.', battle: 'Battle', fight: 'Start the battle',
    battleHint: 'In landscape: ← / → to move, ↑ to jump, A to attack, B for the special move.',
  },
  es: {
    battleOrientation: "Para jugar cómodamente, gira el teléfono en horizontal.", battleStars: "Estrellas",
    huntOrientation: "Para la búsqueda, mantén el teléfono en vertical.",
    rotatePortrait: "Gira el teléfono a vertical para continuar la búsqueda.",
    rotateLandscape: "Gira el teléfono en horizontal para comenzar la batalla.",
    landscapeReady: "Perfecto — orientación horizontal detectada.",
    huntComplete: "Búsqueda completada · 10/10",
    bossIncoming: "El guardián del territorio aparece…",
    pause: "Pausa", resume: "Continuar", restartLevel: "Reiniciar nivel", discoveries: "Mis descubrimientos",
    pauseHint: "El juego está en pausa.", performance: "Rendimiento", fps: "FPS", jank: "Tirones", worstFrame: "Peor frame",
    testTools: "Atajos de prueba",
    testWarning: "Herramientas temporales. Simular una victoria cambia el progreso en este dispositivo.",
    testWin: "Simular una victoria",

    musicStart: "Activar la música",
    musicStop: "Silenciar la música",
    installApp: "Instalar la app",

    hofLead: "Las mejores puntuaciones se guardan en este dispositivo.",
    points: "Puntos totales",
    runs: "Partidas guardadas",
    players: "Jugadores",
    emptyScores: "Aún no hay puntuaciones. Completa una búsqueda para añadir la tuya.",
    localScores: "Las puntuaciones se guardan en este navegador.",
    country: "País",
    progress: "Progreso",
    hits: "Golpes",
    time: "Tiempo",
    bonusDetail: "Detalles de bonus",

    defeat: 'Derrota…',
    language: 'Idioma', ready: '¿Listo para la búsqueda?', lead: 'Explora el Salento, recoge tesoros y gana las batallas para desbloquear los mapas.',
    start: 'Iniciar la búsqueda', bonus: 'Mis descubrimientos', home: 'Inicio', loading: 'Cargando…', level: 'Nivel',
    continue: 'Continuar la búsqueda', replay: 'Volver a jugar', replayLevel: 'Repetir un nivel', newGame: 'Nueva partida', chooseLevel: 'Elegir un nivel', confirmNewGame: '¿Borrar el progreso de esta partida y volver a empezar desde el nivel 1?', confirm: 'Sí, reiniciar', cancel: 'Cancelar', complete: '¡Has completado las nueve búsquedas!',
    bonusLead: 'La búsqueda continúa. Las visitas y los QR son opcionales: explóralos a tu ritmo.',
    maps: 'Explorar un mapa', mapHint: 'Encuentra los lugares en el Salento real.', open: 'Explorar', locked: 'Por desbloquear',
    passport: 'Pasaporte y QR', passportHint: 'Consulta tus visitas y valida un código QR.', passportOpen: 'Abrir mi pasaporte',
    more: 'Clasificaciones', won: '¡Batalla ganada!', unlocked: 'Mapa desbloqueado',
    name: '¿Tu nombre / apodo?', player: 'Jugador', editPlayer: 'Editar', briefing: 'Tu misión', mission: 'Encuentra los diez lugares indicados y gana la batalla.',
    reward: 'Gana la batalla para desbloquear el mapa real.', battle: 'Batalla', fight: 'Iniciar la batalla',
    battleHint: 'En horizontal: ← / → para moverte, ↑ para saltar, A para atacar, B para el especial.',
  },
};
export const copy = { ...(messages[LANG] || messages.en) };

function refreshCopy() {
  const next = messages[LANG] || messages.en;
  Object.keys(copy).forEach((key) => {
    if (!(key in next)) delete copy[key];
  });
  Object.assign(copy, next);
}

if (typeof window !== 'undefined') {
  window.addEventListener('hirundu:language', refreshCopy);
}
