(() => {
  const text = {
    fr: {language:'Langue',title:'Même univers. Plus de clarté.',intro:'Propositions isolées : les niveaux jouables restent inchangés. Ces scènes sont des maquettes, pas des captures du jeu.',style:'Les repères communs',styleNote:'Le bleu nuit reste celui de l’accueil. Dans les chasses, on conserve le ciel, l’ivoire et l’encre marine.',sky:'Ciel',paper:'Ivoire',ink:'Encre',action:'Action',gold:'Or',type:'Une lecture familière',typeNote:'Police système pour jouer. Compteurs monospace. Titres Barlow sur l’accueil.',continue:'Continuer',back:'Retour',locked:'Verrouillé',layout:'Chaque mode garde sa place',mode:'Mode',size:'Format',version:'Version',classic:'Classique · 1 / 2 / 9',arkanoid:'Arkanoid · 3 / 5 / 7',flight:'Vol · 4 / 6 / 8',battle:'Bataille · paysage',proposed:'Proposition',baseline:'Référence reconstituée',read:'Lire →',launch:'Lancer',close:'Fermer',attack:'Attaquer',pause:'Pause',question:'À Giurdignano, trouve la crypte dédiée à San Salvatore, un lieu encore mystérieux de notre voyage.',footnote:'La comparaison garde le même décor et la même taille de scène. Elle ne valide pas encore le cadrage, les collisions ou les performances du jeu réel.',notes:{classic:'Classique : conserver la colonne des dix découvertes à gauche et les déplacements sur la carte. Retoucher seulement les textes et les commandes.',arkanoid:'Arkanoid : préserver les 74 px de dialogue et la grande aire jouable. Question complète accessible au toucher ; commandes de 44 px minimum.',flight:'Vol : garder le pilotage superposé et la colonne de progression. Agrandir Pause sans réduire l’aire de vol.',battle:'Bataille : paysage, informations de combat en haut, commandes séparées en bas. La scène paysage peut défiler horizontalement sur téléphone.'},scene:'Scène',arena:'Aire du décor dans cette maquette',demo:'Démonstration visuelle uniquement',pauseText:'Dans le jeu, Pause suspend la partie. Ici, cette scène ne fait tourner aucun moteur de jeu.',direction:['Haut','Gauche','Droite','Bas']},
    it: {language:'Lingua',title:'Stesso universo. Più chiarezza.',intro:'Proposte isolate: i livelli giocabili restano invariati. Queste scene sono modelli, non schermate del gioco.',style:'Riferimenti comuni',styleNote:'Il blu notte resta nella home. Nelle cacce manteniamo cielo, avorio e blu scuro.',sky:'Cielo',paper:'Avorio',ink:'Inchiostro',action:'Azione',gold:'Oro',type:'Una lettura familiare',typeNote:'Font di sistema nel gioco. Contatori monospazio. Titoli Barlow nella home.',continue:'Continua',back:'Indietro',locked:'Bloccato',layout:'Ogni modalità mantiene il suo spazio',mode:'Modalità',size:'Formato',version:'Versione',classic:'Classica · 1 / 2 / 9',arkanoid:'Arkanoid · 3 / 5 / 7',flight:'Volo · 4 / 6 / 8',battle:'Battaglia · orizzontale',proposed:'Proposta',baseline:'Riferimento ricostruito',read:'Leggi →',launch:'Lancia',close:'Chiudi',attack:'Attacca',pause:'Pausa',question:'A Giurdignano, trova la cripta dedicata a San Salvatore, un luogo ancora misterioso del nostro viaggio.',footnote:'Il confronto mantiene lo stesso sfondo e le stesse dimensioni. Non convalida ancora inquadratura, collisioni o prestazioni del gioco reale.',notes:{classic:'Classica: mantenere la colonna delle dieci scoperte a sinistra e i movimenti sulla mappa. Ritoccare solo testi e comandi.',arkanoid:'Arkanoid: mantenere i 74 px del dialogo e l’ampia area giocabile. Domanda completa al tocco; comandi di almeno 44 px.',flight:'Volo: mantenere i comandi sovrapposti e la colonna dei progressi. Ingrandire Pausa senza ridurre l’area di volo.',battle:'Battaglia: orizzontale, informazioni in alto e comandi in basso. La scena può scorrere orizzontalmente sul telefono.'},scene:'Scena',arena:'Area dello sfondo in questo modello',demo:'Solo dimostrazione visiva',pauseText:'Nel gioco, Pausa sospende la partita. Qui non è in esecuzione alcun motore di gioco.',direction:['Su','Sinistra','Destra','Giù']},
    en: {language:'Language',title:'Same world. More clarity.',intro:'Isolated proposals: playable levels stay unchanged. These scenes are mockups, not game screenshots.',style:'Shared visual references',styleNote:'Midnight blue stays on the home screen. Hunts keep sky blue, ivory and navy ink.',sky:'Sky',paper:'Ivory',ink:'Ink',action:'Action',gold:'Gold',type:'Familiar reading',typeNote:'System font in play. Monospace counters. Barlow headings on the home screen.',continue:'Continue',back:'Back',locked:'Locked',layout:'Each mode keeps its own space',mode:'Mode',size:'Size',version:'Version',classic:'Classic · 1 / 2 / 9',arkanoid:'Arkanoid · 3 / 5 / 7',flight:'Flight · 4 / 6 / 8',battle:'Battle · landscape',proposed:'Proposal',baseline:'Reconstructed reference',read:'Read →',launch:'Launch',close:'Close',attack:'Attack',pause:'Pause',question:'In Giurdignano, find the crypt dedicated to San Salvatore, a mysterious place on our journey.',footnote:'Both versions use the same scenery and scene dimensions. This does not yet validate framing, collisions or performance in the actual game.',notes:{classic:'Classic: retain the ten discoveries in a left column and movement across the map. Refine text and controls only.',arkanoid:'Arkanoid: preserve the 74 px dialogue and large play area. Tap for the full question; touch targets at least 44 px.',flight:'Flight: retain the overlaid controls and progress column. Enlarge Pause without shrinking the flight area.',battle:'Battle: landscape, combat information above and separate controls below. The landscape scene can scroll horizontally on phones.'},scene:'Scene',arena:'Scenery area in this mockup',demo:'Visual demonstration only',pauseText:'In the game, Pause suspends play. This scene does not run a game engine.',direction:['Up','Left','Right','Down']},
    es: {language:'Idioma',title:'Mismo universo. Más claridad.',intro:'Propuestas aisladas: los niveles jugables no cambian. Estas escenas son maquetas, no capturas del juego.',style:'Referencias comunes',styleNote:'El azul noche permanece en el inicio. Las búsquedas conservan cielo, marfil y azul marino.',sky:'Cielo',paper:'Marfil',ink:'Tinta',action:'Acción',gold:'Oro',type:'Una lectura familiar',typeNote:'Fuente del sistema para jugar. Contadores monoespaciados. Títulos Barlow en el inicio.',continue:'Continuar',back:'Volver',locked:'Bloqueado',layout:'Cada modo conserva su espacio',mode:'Modo',size:'Formato',version:'Versión',classic:'Clásico · 1 / 2 / 9',arkanoid:'Arkanoid · 3 / 5 / 7',flight:'Vuelo · 4 / 6 / 8',battle:'Batalla · horizontal',proposed:'Propuesta',baseline:'Referencia reconstruida',read:'Leer →',launch:'Lanzar',close:'Cerrar',attack:'Atacar',pause:'Pausa',question:'En Giurdignano, encuentra la cripta dedicada a San Salvatore, un lugar misterioso de nuestro viaje.',footnote:'La comparación mantiene el mismo fondo y tamaño. Aún no valida el encuadre, las colisiones ni el rendimiento del juego real.',notes:{classic:'Clásico: conservar las diez exploraciones en la columna izquierda y el movimiento por el mapa. Ajustar solo textos y controles.',arkanoid:'Arkanoid: conservar los 74 px del diálogo y la gran zona jugable. Tocar para leer la pregunta; botones de al menos 44 px.',flight:'Vuelo: conservar el control superpuesto y la columna de progreso. Ampliar Pausa sin reducir la zona de vuelo.',battle:'Batalla: horizontal, información arriba y controles separados abajo. La escena puede desplazarse horizontalmente en el teléfono.'},scene:'Escena',arena:'Área del fondo en esta maqueta',demo:'Solo demostración visual',pauseText:'En el juego, Pausa suspende la partida. Esta escena no ejecuta ningún motor de juego.',direction:['Arriba','Izquierda','Derecha','Abajo']}
  };
  const preserved={fr:['↑ Saut','↓ Plongée','↯ Esquive','B · Spécial','Bataille : conserver les commandes, mouvements, boss et transition paysage existants. Seuls de petits ajustements de lisibilité seront proposés.'],it:['↑ Salto','↓ Picchiata','↯ Schivata','B · Speciale','Battaglia: mantenere comandi, movimenti, boss e transizione orizzontale esistenti. Solo piccoli ritocchi di leggibilità.'],en:['↑ Jump','↓ Dive','↯ Dodge','B · Special','Battle: preserve the existing controls, movements, bosses and landscape transition. Only small readability adjustments will be proposed.'],es:['↑ Salto','↓ Picado','↯ Esquiva','B · Especial','Batalla: conservar controles, movimientos, jefes y transición horizontal existentes. Solo pequeños ajustes de legibilidad.']};
  for(const lang of Object.keys(text)){const p=preserved[lang];Object.assign(text[lang],{jump:p[0],dive:p[1],dodge:p[2],special:p[3]});text[lang].notes.battle=p[4];}
  const $ = selector => document.querySelector(selector);
  let language='fr';
  let position={x:52,y:64};
  const dialog=$('#detail');
  function showDialog(title,body){$('#dialog-title').textContent=title;$('#dialog-text').textContent=body;dialog.showModal();}
  function geometry(){const stage=$('#stage').getBoundingClientRect(),area=$('.arena').getBoundingClientRect(),w=text[language];$('#geometry').textContent=`${w.scene} ${Math.round(stage.width)} × ${Math.round(stage.height)} · ${w.arena} ${Math.round(area.width)} × ${Math.round(area.height)} px`;}
  function render(){const w=text[language],mode=$('#mode').value,size=Number($('#size').value);document.documentElement.lang=language;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=w[el.dataset.i18n]);$('#stage').className=`stage ${$('#version').value} ${mode}`;$('#stage').style.width=(mode==='battle'?740:size)+'px';$('#stage').style.height=(mode==='battle'?360:size===320?568:700)+'px';$('#mode-note').textContent=w.notes[mode];$('#question-text').textContent=w.question;$('#main-action').textContent=mode==='battle'?w.attack:w.launch;$('#pause').setAttribute('aria-label',w.pause);$('#question-open').setAttribute('aria-label',w.question+' '+w.read);$('#level-label').textContent={classic:'01',arkanoid:'03',flight:'04',battle:'BATTLE'}[mode];$('#interaction').textContent='';$('#sample-status').textContent='';position={x:mode==='battle'?25:52,y:mode==='flight'?66:64};$('.bird').style.left=position.x+'%';$('.bird').style.top=mode==='arkanoid'?'calc(100% - 74px)':position.y+'%';$('.paddle').style.left=position.x+'%';document.querySelectorAll('[data-direction]').forEach(b=>b.setAttribute('aria-label',w.direction[['up','left','right','down'].indexOf(b.dataset.direction)]));geometry();}
  $('#language').addEventListener('change',e=>{language=e.target.value;render();});
  ['#mode','#size','#version'].forEach(id=>$(id).addEventListener('change',render));
  $('#pause').addEventListener('click',()=>showDialog(text[language].pause,text[language].pauseText));
  $('#question-open').addEventListener('click',()=>showDialog('Tarantula',text[language].question));
  document.querySelectorAll('[data-direction]').forEach(button=>button.addEventListener('click',()=>{const dir=button.dataset.direction;position.x=Math.max(18,Math.min(82,position.x+(dir==='left'?-8:dir==='right'?8:0)));position.y=Math.max(15,Math.min(75,position.y+(dir==='up'?-8:dir==='down'?8:0)));$('.bird').style.left=position.x+'%';$('.bird').style.top=$('#mode').value==='arkanoid'?'calc(100% - 74px)':position.y+'%';$('.paddle').style.left=position.x+'%';$('#interaction').textContent=text[language].demo;}));
  document.querySelectorAll('[data-battle]').forEach(b=>b.addEventListener('click',()=>{$('#interaction').textContent=text[language].demo;}));
  $('#main-action').addEventListener('click',()=>{$('#interaction').textContent=text[language].demo;});
  document.querySelectorAll('[data-demo]').forEach(b=>b.addEventListener('click',()=>{$('#sample-status').textContent=text[language].demo;}));
  if(window.innerWidth<430)$('#size').value='320';
  window.addEventListener('resize',geometry);
  render();
})();
